# Generated by Django 3.2.8 on 2021-11-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muscle', models.CharField(max_length=50)),
                ('intesityLevel', models.IntegerField()),
                ('volumeLevel', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
