# Generated by Django 3.2.8 on 2021-12-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapi', '0002_auto_20211109_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='user',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='volumeLevel',
        ),
        migrations.AddField(
            model_name='workout',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workout',
            name='description',
            field=models.TextField(max_length=100),
        ),
    ]
